apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  app.properties: |
    APP_ENV=production
    LOG_LEVEL=info
  db-config.json: |
    {
      "host": "db.example.com",
      "port": 3306,
      "username": "root"
    }