apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
    - name: app-container
      image: busybox
      command: [ "sleep", "3600" ] # 保持容器运行
      volumeMounts:
        - name: config-volume
          mountPath: "/etc/config"  # 挂载到容器内的 /etc/config 目录
          readOnly: true
  volumes:
    - name: config-volume
      configMap:
        name: my-config
