apiVersion: v1
kind: Pod
metadata:
  name: pv-test-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: [ "sh", "-c", "echo 'Hello from PV' > /mnt/data.txt && sleep 3600" ]
      volumeMounts:
        - name: storage
          mountPath: /mnt  # Pod 内部挂载路径
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: example-pvc  # 绑定 PVC
