# 使用官方 Python 镜像
FROM python:3.9-slim

# 设置工作目录
WORKDIR /app

# 复制当前目录内容到容器内的 /app
COPY . /app

# 安装依赖
RUN pip install -r requirement.txt

# 暴露容器内的端口 8080
EXPOSE 8080

# 启动应用
CMD ["python", "main.py"]
