apiVersion: v1
kind: Pod
metadata:
  name: downward-api-demo
  labels:
    app: downward-api
spec:
  containers:
  - name: test-container
    image: busybox
    command: [ "sh", "-c", "echo 'Pod Name: $POD_NAME, Pod IP: $POD_IP, Node Name: $NODE_NAME' && sleep 3600" ]
    env:
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
