apiVersion: v1
kind: Pod
metadata:
  name: downward-api-demo-volume
  labels:
    app: downward-api
spec:
  containers:
  - name: test-container
    image: busybox
    command: [ "sh", "-c", "cat /etc/pod-info/pod_name && cat /etc/pod-info/pod_ip && cat /etc/pod-info/node_name && sleep 3600" ]
    volumeMounts:
      - name: podinfo
        mountPath: /etc/pod-info
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "pod_name"
            fieldRef:
              fieldPath: metadata.name
          - path: "pod_ip"
            fieldRef:
              fieldPath: status.podIP
          - path: "node_name"
            fieldRef:
              fieldPath: spec.nodeName
